# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -DsuiteXmlFile=testSuits/testng.xml'
  
- script: |
   
    mvn test
    
    # Run your script to generate/update the HTML file based on the test results
    /full/path/to/generate_html_script.sh

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/Reports' 
    artifactName: 'UpdatedExtentReport' 
    publishLocation: 'Container'