# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -DsuiteXmlFile=testSuits/testng.xml'
  
- script: |
    # Run your tests using testng.xml
    mvn test -DsuiteXmlFile=path/to/your/testng.xml
    
    # Run the script to update all files within the 'reports' folder
    chmod +x update_reports.sh  # Ensure script has execute permissions
    ./update_reports.sh Reports
  displayName: 'Run Tests and Update Reports'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/Reports' 
    artifactName: 'UpdatedExtentReport' 
    publishLocation: 'Container'